const { downloadMediaMessage, delay } = require('@whiskeysockets/baileys');

const ppCache = new Map();

/**
 * Command ya kupata profile picture
 */
async function getProfilePictureCommand(sock, chatId, msg) {
  try {
    const text = msg.message?.conversation || msg.message?.extendedTextMessage?.text || "";
    const args = text.split(' ');
    const ctx = msg.message?.extendedTextMessage?.contextInfo;

    let targetJids = [];

    if (ctx?.mentionedJid?.length > 0) {
      targetJids = ctx.mentionedJid;
    } else if (ctx?.participant) {
      targetJids = [ctx.participant];
    } else if (args[1] && args[1].match(/^\d+$/)) {
      targetJids = [`${args[1]}@s.whatsapp.net`];
    } else {
      targetJids = [msg.key.participant || msg.key.remoteJid];
    }

    for (const jid of targetJids.slice(0, 5)) {
      await sendEnhancedPP(sock, chatId, jid, msg);
      await delay(1500);
    }

  } catch (error) {
    console.error('Error in PP Command:', error);
    await sock.sendMessage(chatId, { text: "❌ Hitilafu imetokea (Error processing request)." });
  }
}

/**
 * Safe fetch na timeout
 */
async function safeProfilePictureUrl(sock, jid, quality = 'image') {
  try {
    return await Promise.race([
      sock.profilePictureUrl(jid, quality),
      new Promise((_, reject) => setTimeout(() => reject(new Error('Timeout')), 5000))
    ]);
  } catch (err) {
    console.log(`Failed to fetch ${quality} for ${jid}:`, err.message);
    return null;
  }
}

/**
 * Kutuma picha yenye fallback + API detection
 */
async function sendEnhancedPP(sock, chatId, targetJid, quotedMsg) {
  let ppUrl;
  let statusMsg = "";

  try {
    if (ppCache.has(targetJid)) {
      ppUrl = ppCache.get(targetJid);
      statusMsg = "♻️ Cached Result";
    } else {
      ppUrl = await safeProfilePictureUrl(sock, targetJid, 'image');
      if (ppUrl) {
        statusMsg = "✅ HD Quality";
      } else {
        ppUrl = await safeProfilePictureUrl(sock, targetJid, 'preview');
        if (ppUrl) {
          statusMsg = "⚠️ Standard Quality (HD Restricted)";
        } else {
          // Hakikisha namba ipo WhatsApp
          const exists = await sock.onWhatsApp(targetJid);
          if (exists?.[0]?.exists) {
            statusMsg = "❌ API Failed (DP exists but not fetched)";
          } else {
            statusMsg = "❌ No DP or Privacy Restricted";
          }
          ppUrl = "https://ui-avatars.com/api/?name=No+DP&background=random&size=512";
        }
      }
      ppCache.set(targetJid, ppUrl);
    }

    const name = await getUserName(sock, targetJid);
    const caption = `✨ *PROFILE PICTURE FETCHED* ✨\n\n` +
                    `👤 *User:* @${targetJid.split('@')[0]}\n` +
                    `📝 *Name:* ${name}\n` +
                    `📊 *Status:* ${statusMsg}\n\n` +
                    `_Generated by Bot_`;

    await sock.sendMessage(chatId, {
      image: { url: ppUrl },
      caption: caption,
      mentions: [targetJid]
    }, { quoted: quotedMsg });

  } catch (err) {
    console.log("Final Fallback Error:", err);
    await sock.sendMessage(chatId, { text: "⚠️ Imeshindikana kupata profile picture." });
  }
}

/**
 * Pata jina la mtumiaji
 */
async function getUserName(sock, jid) {
  try {
    const contact = sock.store?.contacts?.[jid];
    if (contact?.name || contact?.notify) return contact.name || contact.notify;

    if (jid.endsWith('@g.us')) {
      const meta = await sock.groupMetadata(jid);
      return meta.subject;
    }
    return "User";
  } catch {
    return "User";
  }
}

module.exports = getProfilePictureCommand;